//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace syntaxer.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("syntaxer.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] csc_exe {
            get {
                object obj = ResourceManager.GetObject("csc_exe", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;!-- Copyright (c)  Microsoft.  All Rights Reserved.  Licensed under the Apache License, Version 2.0.  See License.txt in the project root for license information. --&gt;
        ///&lt;configuration&gt;
        ///  &lt;runtime&gt;
        ///    &lt;gcServer enabled=&quot;true&quot; /&gt;
        ///    &lt;gcConcurrent enabled=&quot;false&quot; /&gt;
        ///    &lt;assemblyBinding xmlns=&quot;urn:schemas-microsoft-com:asm.v1&quot;&gt;
        ///      &lt;dependentAssembly&gt;
        ///        &lt;assemblyIdentity name=&quot;Microsoft.CodeAnalysis&quot; publicKeyToken=&quot;31bf3856ad364e35&quot; culture=&quot;neutral&quot; /&gt;        /// [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string csc_exe_config {
            get {
                return ResourceManager.GetString("csc_exe_config", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] csc_rsp {
            get {
                object obj = ResourceManager.GetObject("csc_rsp", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] csi_exe {
            get {
                object obj = ResourceManager.GetObject("csi_exe", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;configuration&gt;
        ///  &lt;runtime&gt;
        ///    &lt;assemblyBinding xmlns=&quot;urn:schemas-microsoft-com:asm.v1&quot;&gt;
        ///      &lt;dependentAssembly&gt;
        ///        &lt;assemblyIdentity name=&quot;Microsoft.CodeAnalysis&quot; publicKeyToken=&quot;31bf3856ad364e35&quot; culture=&quot;neutral&quot; /&gt;
        ///        &lt;bindingRedirect oldVersion=&quot;0.0.0.0-2.0.0.0&quot; newVersion=&quot;2.0.0.0&quot; /&gt;
        ///      &lt;/dependentAssembly&gt;
        ///    &lt;/assemblyBinding&gt;
        ///    &lt;assemblyBinding xmlns=&quot;urn:schemas-microsoft-com:asm.v1&quot;&gt;
        ///      &lt;dependentAssembly&gt;
        ///        &lt;assembly [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string csi_exe_config {
            get {
                return ResourceManager.GetString("csi_exe_config", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] csi_rsp {
            get {
                object obj = ResourceManager.GetObject("csi_rsp", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] CSSRoslynProvider {
            get {
                object obj = ResourceManager.GetObject("CSSRoslynProvider", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] Esent_Interop {
            get {
                object obj = ResourceManager.GetObject("Esent_Interop", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] Intellisense_Common {
            get {
                object obj = ResourceManager.GetObject("Intellisense_Common", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] Microsoft_Build {
            get {
                object obj = ResourceManager.GetObject("Microsoft_Build", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] Microsoft_Build_Framework {
            get {
                object obj = ResourceManager.GetObject("Microsoft_Build_Framework", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] Microsoft_Build_Tasks_CodeAnalysis {
            get {
                object obj = ResourceManager.GetObject("Microsoft_Build_Tasks_CodeAnalysis", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] Microsoft_Build_Tasks_Core {
            get {
                object obj = ResourceManager.GetObject("Microsoft_Build_Tasks_Core", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] Microsoft_Build_Utilities_Core {
            get {
                object obj = ResourceManager.GetObject("Microsoft_Build_Utilities_Core", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] Microsoft_CodeAnalysis {
            get {
                object obj = ResourceManager.GetObject("Microsoft_CodeAnalysis", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] Microsoft_CodeAnalysis_CSharp {
            get {
                object obj = ResourceManager.GetObject("Microsoft_CodeAnalysis_CSharp", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] Microsoft_CodeAnalysis_CSharp_Scripting {
            get {
                object obj = ResourceManager.GetObject("Microsoft_CodeAnalysis_CSharp_Scripting", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] Microsoft_CodeAnalysis_CSharp_Workspaces {
            get {
                object obj = ResourceManager.GetObject("Microsoft_CodeAnalysis_CSharp_Workspaces", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] Microsoft_CodeAnalysis_Elfie {
            get {
                object obj = ResourceManager.GetObject("Microsoft_CodeAnalysis_Elfie", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] Microsoft_CodeAnalysis_Scripting {
            get {
                object obj = ResourceManager.GetObject("Microsoft_CodeAnalysis_Scripting", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] Microsoft_CodeAnalysis_VisualBasic {
            get {
                object obj = ResourceManager.GetObject("Microsoft_CodeAnalysis_VisualBasic", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] Microsoft_CodeAnalysis_VisualBasic_Workspaces {
            get {
                object obj = ResourceManager.GetObject("Microsoft_CodeAnalysis_VisualBasic_Workspaces", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] Microsoft_CodeAnalysis_Workspaces {
            get {
                object obj = ResourceManager.GetObject("Microsoft_CodeAnalysis_Workspaces", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] Microsoft_CodeAnalysis_Workspaces_Desktop {
            get {
                object obj = ResourceManager.GetObject("Microsoft_CodeAnalysis_Workspaces_Desktop", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] Microsoft_CodeDom_Providers_DotNetCompilerPlatform {
            get {
                object obj = ResourceManager.GetObject("Microsoft_CodeDom_Providers_DotNetCompilerPlatform", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] Microsoft_CSharp_Core {
            get {
                object obj = ResourceManager.GetObject("Microsoft_CSharp_Core", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] Microsoft_DiaSymReader_Native_amd64 {
            get {
                object obj = ResourceManager.GetObject("Microsoft_DiaSymReader_Native_amd64", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] Microsoft_DiaSymReader_Native_x86 {
            get {
                object obj = ResourceManager.GetObject("Microsoft_DiaSymReader_Native_x86", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] Microsoft_VisualBasic_Core {
            get {
                object obj = ResourceManager.GetObject("Microsoft_VisualBasic_Core", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] Microsoft_VisualStudio_RemoteControl {
            get {
                object obj = ResourceManager.GetObject("Microsoft_VisualStudio_RemoteControl", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] Microsoft_Win32_Primitives {
            get {
                object obj = ResourceManager.GetObject("Microsoft_Win32_Primitives", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] RoslynIntellisense {
            get {
                object obj = ResourceManager.GetObject("RoslynIntellisense", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] System_AppContext {
            get {
                object obj = ResourceManager.GetObject("System_AppContext", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] System_Collections_Immutable {
            get {
                object obj = ResourceManager.GetObject("System_Collections_Immutable", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] System_Composition_AttributedModel {
            get {
                object obj = ResourceManager.GetObject("System_Composition_AttributedModel", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] System_Composition_Convention {
            get {
                object obj = ResourceManager.GetObject("System_Composition_Convention", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] System_Composition_Hosting {
            get {
                object obj = ResourceManager.GetObject("System_Composition_Hosting", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] System_Composition_Runtime {
            get {
                object obj = ResourceManager.GetObject("System_Composition_Runtime", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] System_Composition_TypedParts {
            get {
                object obj = ResourceManager.GetObject("System_Composition_TypedParts", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] System_Console {
            get {
                object obj = ResourceManager.GetObject("System_Console", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] System_Diagnostics_FileVersionInfo {
            get {
                object obj = ResourceManager.GetObject("System_Diagnostics_FileVersionInfo", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] System_Diagnostics_Process {
            get {
                object obj = ResourceManager.GetObject("System_Diagnostics_Process", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] System_Diagnostics_StackTrace {
            get {
                object obj = ResourceManager.GetObject("System_Diagnostics_StackTrace", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] System_IO_Compression {
            get {
                object obj = ResourceManager.GetObject("System_IO_Compression", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] System_IO_FileSystem {
            get {
                object obj = ResourceManager.GetObject("System_IO_FileSystem", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] System_IO_FileSystem_DriveInfo {
            get {
                object obj = ResourceManager.GetObject("System_IO_FileSystem_DriveInfo", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] System_IO_FileSystem_Primitives {
            get {
                object obj = ResourceManager.GetObject("System_IO_FileSystem_Primitives", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] System_IO_Pipes {
            get {
                object obj = ResourceManager.GetObject("System_IO_Pipes", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] System_Reflection_Metadata {
            get {
                object obj = ResourceManager.GetObject("System_Reflection_Metadata", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] System_Runtime_InteropServices_RuntimeInformation {
            get {
                object obj = ResourceManager.GetObject("System_Runtime_InteropServices_RuntimeInformation", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] System_Security_AccessControl {
            get {
                object obj = ResourceManager.GetObject("System_Security_AccessControl", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] System_Security_Claims {
            get {
                object obj = ResourceManager.GetObject("System_Security_Claims", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] System_Security_Cryptography_Algorithms {
            get {
                object obj = ResourceManager.GetObject("System_Security_Cryptography_Algorithms", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] System_Security_Cryptography_Encoding {
            get {
                object obj = ResourceManager.GetObject("System_Security_Cryptography_Encoding", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] System_Security_Cryptography_Primitives {
            get {
                object obj = ResourceManager.GetObject("System_Security_Cryptography_Primitives", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] System_Security_Cryptography_X509Certificates {
            get {
                object obj = ResourceManager.GetObject("System_Security_Cryptography_X509Certificates", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] System_Security_Principal_Windows {
            get {
                object obj = ResourceManager.GetObject("System_Security_Principal_Windows", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] System_Text_Encoding_CodePages {
            get {
                object obj = ResourceManager.GetObject("System_Text_Encoding_CodePages", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] System_Threading_Tasks_Dataflow {
            get {
                object obj = ResourceManager.GetObject("System_Threading_Tasks_Dataflow", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] System_Threading_Thread {
            get {
                object obj = ResourceManager.GetObject("System_Threading_Thread", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] System_ValueTuple {
            get {
                object obj = ResourceManager.GetObject("System_ValueTuple", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] System_Xml_ReaderWriter {
            get {
                object obj = ResourceManager.GetObject("System_Xml_ReaderWriter", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] System_Xml_XmlDocument {
            get {
                object obj = ResourceManager.GetObject("System_Xml_XmlDocument", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] System_Xml_XPath {
            get {
                object obj = ResourceManager.GetObject("System_Xml_XPath", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] System_Xml_XPath_XDocument {
            get {
                object obj = ResourceManager.GetObject("System_Xml_XPath_XDocument", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] vbc {
            get {
                object obj = ResourceManager.GetObject("vbc", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;!-- Copyright (c)  Microsoft.  All Rights Reserved.  Licensed under the Apache License, Version 2.0.  See License.txt in the project root for license information. --&gt;
        ///&lt;configuration&gt;
        ///  &lt;runtime&gt;
        ///    &lt;gcServer enabled=&quot;true&quot; /&gt;
        ///    &lt;gcConcurrent enabled=&quot;false&quot; /&gt;
        ///    &lt;assemblyBinding xmlns=&quot;urn:schemas-microsoft-com:asm.v1&quot;&gt;
        ///      &lt;dependentAssembly&gt;
        ///        &lt;assemblyIdentity name=&quot;Microsoft.CodeAnalysis&quot; publicKeyToken=&quot;31bf3856ad364e35&quot; culture=&quot;neutral&quot; /&gt;        /// [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string vbc_exe {
            get {
                return ResourceManager.GetString("vbc_exe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] vbc1 {
            get {
                object obj = ResourceManager.GetObject("vbc1", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] VBCSCompiler {
            get {
                object obj = ResourceManager.GetObject("VBCSCompiler", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;!-- Copyright (c)  Microsoft.  All Rights Reserved.  Licensed under the Apache License, Version 2.0.  See License.txt in the project root for license information. --&gt;
        ///&lt;configuration&gt;
        ///  &lt;runtime&gt;
        ///    &lt;gcServer enabled=&quot;true&quot; /&gt;
        ///    &lt;gcConcurrent enabled=&quot;false&quot; /&gt;
        ///    &lt;assemblyBinding xmlns=&quot;urn:schemas-microsoft-com:asm.v1&quot;&gt;
        ///      &lt;dependentAssembly&gt;
        ///        &lt;assemblyIdentity name=&quot;Microsoft.CodeAnalysis&quot; publicKeyToken=&quot;31bf3856ad364e35&quot; culture=&quot;neutral&quot; /&gt;        /// [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string VBCSCompiler_exe {
            get {
                return ResourceManager.GetString("VBCSCompiler_exe", resourceCulture);
            }
        }
    }
}
